matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
sudo: required
language: ruby
rvm:
  - 2.6.3
cache: bundler
addons:
  apt:
    update: true
before_install:
  - nvm install node
  # This is a workaround for npm install
  # https://github.com/npm/npm/issues/20203
  - npm config set strict-ssl false
env:
  global:
    - JAVA_OPTS="java.awt.headless=true"
    - RUBY_VER="2.6.3"
script:
  - sudo ./ubuntu.sh
  - ./install-gems.sh
  - plantuml -testdot
  - export NODE_PATH=$(npm root -g)
  - which latexml xml2rfc idnits
  # test metanorma output and
